---
- hosts: raspberry
  tasks:
    - name: Add some lines
      become: yes
      become_user: root
      blockinfile:
        path: /root/.bashrc
        block: |
        # some more ls aliases
        alias ll='ls -alF'
        alias la='ls -A'
        alias l='ls -CF'


    - name: Display the config
      debug:
        msg: "The hostname is ?"



   
