---
- hosts: raspberry
  tasks:
    - name: Add a line to a file if the file does not exist, without passing regex
      become: yes
      become_user: root
      lineinfile:
        path: /root/.bashrc
        line: # some more ls aliases
        line: alias ll='ls -alF'
        line: alias la='ls -A'
        line: alias l='ls -CF'
        create: yes
    - name: Display the config
      debug:
        msg: "The hostname is ?"
